---
- name: Create Portainer folder if enable_persistent_data is false
  when: not enable_persistent_data
  file:
    path: "{{ docker_data_path }}/portainer/data"
    state: directory
    mode: 0765
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create Portainer container
  become: true
  become_user: "{{ username }}"
  community.docker.docker_container:
    name: portainer
    image: "cr.portainer.io/portainer/portainer-ce:2.11.0"
    pull: true
    state: started
    volumes:
      - "{{ docker_data_path }}/portainer/data:/data:rw"
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    env:
      "PUID": "{{ username_uid | string }}"
      "PGID": "{{ username_gid | string }}"
      "TZ": "{{ timezone }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ docker_proxy_network }}"
    ports:
      - 9000:9000
    security_opts:
      - "no-new-privileges:true"
    labels:
      "traefik.enable": "true"
      "traefik.http.routers.portainer.entrypoints": "http"
      "traefik.http.routers.portainer.rule": "Host(`portainer.{{ dns_domain_name }}`)"
      "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme": "https"
      "traefik.http.routers.portainer.middlewares": "portainer-https-redirect"
      "traefik.http.routers.portainer-secure.entrypoints": "https"
      "traefik.http.routers.portainer-secure.rule": "Host(`portainer.{{ dns_domain_name }}`)"
      "traefik.http.routers.portainer-secure.tls": "true"
      "traefik.http.routers.portainer-secure.service": "portainer"
      "traefik.http.services.portainer.loadbalancer.server.port": "9000"
      "traefik.docker.network": "{{ docker_proxy_network }}"
