---
- name: Ubuntu specific tasks
  become: yes
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
  - name: Remove cloud-config to avoid boot delay
    apt:
      name: cloud-config
      state: absent
    when: enable_cloudconfig | default(false)

  - name: Make sure iSCSId and Open-iSCSId services are disabled
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - iscsid
      - open-iscsi
    register: svc_result
    failed_when: svc_result == 1

  - name: Install the apt mirror list
    template:
      src: sources.list.j2
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644
    tags: mirrors

  - name: Update cache
    apt:
      update_cache: true
      cache_valid_time: 3600

- name: Generate the locale (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

# - name: Replace the hostname entry with our own
#   ansible.builtin.lineinfile:
#     path: /etc/hosts
#     insertafter: ^127\.0\.0\.1 *localhost
#     line: "127.0.0.1 {{ inventory_hostname }}"
#     owner: root
#     group: root
#     mode: '0644'
